### PR TITLE
HttpClient

### PR DESCRIPTION
**Pull request by cheeseonamonkey**

### CODE REVIEW

**Comment by cheeseonamonkey** [comment]
As far as I know there is not actually any merge conflict, we can just use the new version.

Diffs are a nightmare.

**Review by GeorgeRay — CHANGES_REQUESTED** [review]
It runs fine now but it does not have the changes I pushed last week. You need to pull/merge the current master to your branch.

**Comment by cheeseonamonkey** [comment]
So there is an actual merge issue

**Comment by GeorgeRay** [comment]
In visual studio, if you sync the project and do a pull. It should let you update your branch to the current master and you can fix the merge conflicts (like you did last time). The last time you had the latest code, but there were a few errors, like the code was never run after the merge.

**Comment by cheeseonamonkey** [comment]
I don't think it's worth it with the amount of changes made to all the web calls

**Pull request closed without merging**
