### PR TITLE
HttpClient

### PR DESCRIPTION
**Pull request by cheeseonamonkey**
Consider this unstable for now but its a start, you can really see the async working as it populates the course list one by one as they come back.

Try it out and see if its conspicuously faster. I was thinking of just putting a timer on as well and timing both methods.

### CODE REVIEW

**Review by TheGeorgeRay — CHANGES_REQUESTED** [review]
What you are seeing is the async effect on populating the form. It is all the same speed. The use of the awaits is causing it to be the same speed. We need to set the code up to run in parallel.

https://www.michalbialecki.com/2018/04/19/how-to-send-many-requests-in-parallel-in-asp-net-core/

**Comment by cheeseonamonkey** [comment]
You're right, but it was still good to start somewhere, and we wanted to update to HttpClient anyway.

I did some tedious experimenting today, timing different web call methods, and I think I've learned a lot:
image

This was only tested on the Courses form, but it appears to be substantially faster this way. The speed difference may even be even more pronounced in the Grading Queue because there are more parallel calls to be made.

**Comment by GeorgeRay** [comment]
Woot woot. I can’t wait to try it out.

George

On Feb 16, 2021, at 10:42, Alexander H <notifications@github.com> wrote:

﻿

You're right, but it was still good to start somewhere, and we wanted to update to HttpClient anyway.

I did some tedious experimenting today, timing different web call methods, and I think I've learned a lot:
[image]<https://user-images.githubusercontent.com/54555500/108100551-4b194880-7043-11eb-8ce9-e244388c13f0.png>

This was only tested on the Courses form, but it appears to be substantially faster this way. The speed difference may even be even more pronounced in the Grading Queue because there are more parallel calls to be made.

**Comment by cheeseonamonkey** [comment]
I encountered a mysterious merge conflict but I think I cleaned it up okay, if needed I'll just make a new PR

**Comment by GeorgeRay** [comment]
First, the refresh speed has greatly improved. I am excited about this.

On the course form when I click on a course I am getting an error of "Error populating students. Object reference not set to an instance of an object." I am guessing this was from the merge conflict. Are you getting this error on your end.

On the CoursesForm, on line 195 there is a curly brace missing that I had to put in to run. Did you fix the merge conflict and not test the code?

**Review by GeorgeRay — CHANGES_REQUESTED** [review]
On the course form when I click on a course I am getting an error of "Error populating students. Object reference not set to an instance of an object." I am guessing this was from the merge conflict. Are you getting this error on your end.

On the CoursesForm, on line 195 there is a curly brace missing that I had to put in to run. Did you fix the merge conflict and not test the code?

**Comment by cheeseonamonkey** [comment]
I'm not getting either issue, so it probably was the merge.

Put in PR #45, as far as I know there is no merge conflict really and we can just use the new version.

**Pull request closed without merging**
