### PR TITLE
adding custom priority form

### PR DESCRIPTION
**Pull request by cheeseonamonkey**
This allows you to set your own priority flags.

Most of the work is done in a local PrioritySettings class in the GradingQueueForm; every settings operation has a respective method. I also added additional property settings to hold the settings persistently.

I do think it is best to have the class and object in GradingQueueForm as its not needed anywhere else (as well as UI stuff to access the settings).

### CODE REVIEW

**Review by GeorgeRay — CHANGES_REQUESTED** [review]
The new form does not pop up in the center of the parent.

When changing priorities, if there is nothing in the priority 1 field, it does not update the other priorities.

I don't think there is a need to set default settings. I think it is okay if a user decides they don't want priorities.

On line 177, there is an console output. Why is there is here? Are you debugging with console and not breakpoints?

It is best practice to put the nested class last.
https://github.com/DotNetAnalyzers/StyleCopAnalyzers/blob/master/documentation/SA1201.md

I think your solution is acceptable for Davis Tech, but can we think of a solutions to let the user have as many or as few as they want.  Maybe a datagridview that the user can edit. Each row would have a priority number and term.

**Comment by cheeseonamonkey** [comment]
This is definitely a far more elegant solution in terms of both UI and code.

Especially became simplified a lot when I changed the priority list type into KeyValuePairs, so we don't need a separate list for every possible priority. And I set up the editable data grid view like you recommended, its actually a pretty easy control to work with programatically.

**Comment by cheeseonamonkey** [comment]
I just realized it might crash if there is no default data. Let me double check first.

**Comment by cheeseonamonkey** [comment]
Fixed

**Comment by cheeseonamonkey** [comment]
We can go over it in the meeting tomorrow if you'd like

**Review by GeorgeRay — CHANGES_REQUESTED** [review]
I like where this is going.
Priority Settings Form:
I cannot remove a priority record.
We need language to say "Assignment Keywords"
Can we make the priority column take an integer and let the user pick it (don't give them a list)?  What if they want 100 priorities? Is it possible to accommodate that?

GradingQueue.cs
You have a default priority of 5 but in the settings form it can go to 9. Should we make the default 999 or 99 or 9. Or better yet, let the user pick default priority number in the priority Settings form.

**Comment by cheeseonamonkey** [comment]
Picking the default as a setting is a good idea, I think I'll do that. I
arbitrarily picked 5 because you could then prioritize or "deprioritize"
from the default.

Do you think giving the user 100 or 1000 priority options is really the
best approach though? I even considered making it 1-20 but I think I ended
up deciding 1-9 was the simplest while still fulfilling any user needs.

Deletion is supposed to be handled automatically with the DataGridView but
it's not very intuitive, I think you have to use the delete key on the
keyboard. I'll add some better UI for deletion.

**Review by GeorgeRay — APPROVED** [review]

**Pull request merged**
