### PR TITLE
issue 9 - crashing when cancelling AccessTokenForm without having ent…

### PR DESCRIPTION
**Pull request by cheeseonamonkey**
…ered an access token.

I added a default check in the main form after the AccessTokenForm dialog. This must be done in the main form (not the AccessTokenForm) because the main form creates the AccessTokenForm dialog and then continues.

This still does not address the possibility that a user has entered an incorrect access token (which may be a brand new issue), it only checks that a user has closed the AccessTokenForm without having entered a token at all.

### CODE REVIEW

**Comment by cheeseonamonkey** [comment]
Oh, I didn't link it with the open issue, let me do that.

**Review by GeorgeRay — CHANGES_REQUESTED** [review]
It would be better to give the user a message instead of closing the app. Let's combine the first and second if statements.

**Comment by cheeseonamonkey** [comment]
I think the first option involving the dialog box would be better

**Comment by GeorgeRay** [comment]
I think the right user experience would be to let the user cancel out of the setting form and then let them close the application if they want to.  I think the loop would keep them from closing out the application.

**Comment by GeorgeRay** [comment]
I think I went about the structure wrong. You are right that it only crashes when a call to the API is made. We need to beef up the logic around each API call not when the form loads.  I am going to close this pull request and create a new issue.

**Pull request closed without merging**
