### PR TITLE
Url crash fix

### PR DESCRIPTION
**Pull request by cheeseonamonkey**
This shouldn't conflict with the other merge at all, or it should only affect the Access Token settings form.

This mainly fixed a crash when invalid URL is first entered.

Also added a link to generate access token once a valid URL is set. It opens this link in the default browser.

### CODE REVIEW

**Review by TheGeorgeRay — CHANGES_REQUESTED** [review]
I thought the program froze when I tested a bad URL. Can you put a wait cursor in the code?
Also, I just noticed the link to the URL to generate a token. That is cool. Nice improvement. The text looks weird next to the Access Token. I think if you put parenthesis around the link it would make it feel like the text size was intentional.

**Comment by cheeseonamonkey** [comment]
There was already a wait cursor for the access token but not the URL

**Review by GeorgeRay — APPROVED** [review]
Looks good.

**Review by GeorgeRay — CHANGES_REQUESTED** [review]
I was getting some weirdness with the app and then finaly got and error that said "Cannot call object that has been disposed. Why did you add the this.Dispose() method. What was it supposed to do?

**Comment by cheeseonamonkey** [comment]
I was under the impression it was good practice to always dispose of the the form after closing...

I probably added it unnecessarily out of habit but it seems you only need to dispose when you open with ShowDialog().

https://stackoverflow.com/questions/39500280/proper-way-to-dispose-a-new-form

Good to know anyway. I'll double check and merge again.

**Comment by GeorgeRay** [comment]
I really am not sure. Will you try to duplicate the errors. Try canceling out of the settings form and check the current profile.

**Comment by cheeseonamonkey** [comment]
Yeah to duplicate you just use the cancel button on the form twice.

I think it is fine just to remove the dispose call in this case, becase we are using the same form object. I should've thought that through better before casually throwing it in there with an unrelated issue.

**Review by GeorgeRay — APPROVED** [review]
Looks Good.

**Review by TheGeorgeRay — APPROVED** [review]

**Pull request merged**
